services:
  eventstore:
    image: eventstore/eventstore:23.6.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  mongo:
    image: mongo:7.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db

  rabbitmq:
    image: rabbitmq:3.12.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - type: volume
        source: rabbitmq-volume-data
        target: /var/lib/rabbitmq

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-volume-data:
  rabbitmq-volume-data:
