#!/bin/sh

git stash -q --keep-index

./gradlew check

status=$?

if [ $status != 0 ]; then
        echo "Gradle check returned non-zero: $status, abort commit"
        exit $status
fi

cd ui

npm run check

status=$?

if [ $status != 0 ]; then
        echo "UI check returned non-zero: $status, abort commit"
        exit $status
fi

git stash pop -q

exit 0
